'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CSI_Library.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [Rainmeter]
        '''Update=1000
        '''Background=#@#Background.png
        '''BackgroundMode=3
        '''BackgroundMargins=0,34,0,14
        '''
        '''[Variables]
        '''fontName=Trebuchet MS
        '''textSize=8
        '''colorBar=235,170,0,255
        '''colorText=255,255,255,205
        '''lX=10
        '''lW=190
        '''lH=14
        '''rX=100
        '''rW=100
        '''rH=14
        ''';BGColor=00FF00
        '''
        '''
        '''; ----------------------------------
        '''; STYLES are used to &quot;centralize&quot; options
        '''; ----------------------------------
        '''
        '''[styleTitle]
        '''StringAlign=Center
        '''StringCase=Upper
        '''StringStyle=Bold
        '''StringEffect=Shadow
        '''FontEffectColor=0,0,0,50
        '''Font [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property CSIFLEX() As String
            Get
                Return ResourceManager.GetString("CSIFLEX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Public ReadOnly Property Rainmeter_3_3_r2461_beta() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Rainmeter_3_3_r2461_beta", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Public ReadOnly Property reports_templates() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("reports_templates", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Public ReadOnly Property repview_needs() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("repview_needs", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
